apiVersion: apps/v1
kind: Deployment
metadata:
  name: a-micro
  namespace: dev
  labels:
    app: myapp
    svc: a-micro
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: a-micro
  template:
    metadata:
      labels:
        svc: a-micro
        app: myapp
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: b-micro
  namespace: dev
  labels:
    app: myapp
    svc: b-micro
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: b-micro
  template:
    metadata:
      labels:
        svc: b-micro
        app: myapp
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: c-micro
  namespace: dev
  labels:
    app: myapp
    svc: c-micro
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: c-micro
  template:
    metadata:
      labels:
        svc: c-micro
        app: myapp
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80